# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17d2e84d36772ca24029ea46f56e262a9bd7e02a8ff4ce0efc52d8ed81a12746dc10c73060037f07453e90c91d291abfa0d3603aa75ef70fa401433ad89624e3

test:
  secret_key_base: 551364fbc401d79b108e373e713c5e74a17367b72f2b4104ad3b3a1359f50899c1fbf72613976f4cce35a8a8f095ce5644ce8457af77004cf27dabc97bb33ea8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
